# Generated by Django 4.1 on 2022-08-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor_Cono', models.CharField(max_length=50)),
                ('precio_Cono', models.CharField(max_length=50)),
                ('cantidad_Cono', models.PositiveIntegerField(blank=True, help_text='Eliga la cantidad a comprar', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaHeladeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreLocal', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
                ('Local', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=50)),
                ('Ruc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Galleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor_Galleta', models.CharField(max_length=100)),
                ('precio_Galleta', models.CharField(max_length=100)),
                ('cantidad_Galleta', models.PositiveIntegerField(blank=True, help_text='Eliga la cantidad a comprar', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Helado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor_Helado', models.CharField(max_length=50)),
                ('precio_Helado', models.CharField(max_length=50)),
                ('cantidad_Helado', models.PositiveIntegerField(blank=True, help_text='Eliga la cantidad a comprar', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pastel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor_Pastel', models.CharField(max_length=100)),
                ('precio_Pastel', models.CharField(max_length=100)),
                ('cantidad_Pastel', models.PositiveIntegerField(blank=True, help_text='Eliga la cantidad a comprar', null=True)),
            ],
        ),
    ]
