# Generated by Django 4.1 on 2022-08-15 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Heladeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaheladeria',
            name='Factura',
            field=models.PositiveIntegerField(blank=True, help_text='Eliga la cantidad a comprar', null=True),
        ),
        migrations.AddField(
            model_name='helado',
            name='EmpresaHeladeria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Helado_list', to='Heladeria.empresaheladeria'),
            preserve_default=False,
        ),
    ]
