# Generated by Django 4.1 on 2022-08-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('precio_materia', models.CharField(max_length=100)),
                ('cantidad_producto', models.CharField(max_length=100)),
            ],
        ),
    ]
