# Generated by Django 4.1 on 2022-08-15 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreLocal', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
                ('Local', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=50)),
                ('Ruc', models.CharField(max_length=50)),
                ('Factura', models.PositiveIntegerField(blank=True, help_text='Eliga la cantidad a comprar', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('cedula_usuario', models.CharField(help_text='Maximo 11 numeros, sin - ', max_length=11)),
                ('numerocelular_usuario', models.CharField(help_text='Maximo 10 numeros con el 0 ', max_length=10)),
                ('direccion_usuario', models.CharField(help_text='Direccion Actual', max_length=100)),
                ('Factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DatosUsuario_list', to='Facturas.factura')),
            ],
        ),
    ]
